const SUPABASE_URL='https://gumzriegzesossdcypak.supabase.co';
const SUPABASE_KEY='sb_publishable_yzHxTr5YWx2CWTGDT3544w_Cp93fdUv';
const db=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let mode='login',user=null,profile=null,photoFile=null,chosenChallenge=null,challengeLimit=30,feedMode='all',lastNotifCount=0,currentScreen='feedScreen';
const reactionLabels={beer:'🍺 Santé',boar:'🐗 Beauf certifié',masterclass:'😂 Masterclass',flipflop:'🩴 Claquettes d’or'};
const reactionEmoji={beer:'🍺',boar:'🐗',masterclass:'😂',flipflop:'🩴'};
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function toast(t){const e=$('#toast');if(!e)return;e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1900)}
function avatarHTML(p,cls='mini-avatar'){return `<div class="${cls}">${p?.avatar_url?`<img src="${esc(p.avatar_url)}" alt="">`:'😎'}</div>`}
function injectV5(){
 const head=$('header .header-actions');if(head&&!$('#notificationsBtn'))head.insertAdjacentHTML('afterbegin','<button id="notificationsBtn" class="round notify-btn" title="Notifications">🔔<span id="notifBadge" class="notif-badge" hidden>0</span></button>');
 const main=$('main');if(main&&!$('#notificationsScreen'))main.insertAdjacentHTML('beforeend','<section id="notificationsScreen" class="screen"><div class="page-head"><button class="page-back">←</button><h1>Notifications</h1><button id="markAllRead" class="link-btn">Tout lire</button></div><div id="notificationsList" class="notifications-list"></div></section><section id="userProfileScreen" class="screen"><div class="page-head"><button class="page-back">←</button><h1>Profil</h1></div><div id="userProfileContent"></div></section>');
 const st=document.createElement('style');st.textContent=`.notify-btn{position:relative}.notif-badge{position:absolute;right:-3px;top:-4px;min-width:19px;height:19px;border-radius:999px;background:#ef5350;color:#fff;font-size:11px;font-weight:900;display:grid;place-items:center;padding:0 4px;border:2px solid #fff}.page-head{height:58px;display:grid;grid-template-columns:48px 1fr auto;align-items:center;gap:8px;padding:7px 12px;background:#fff;border-bottom:1px solid var(--line);position:sticky;top:64px;z-index:21}.page-head h1{font-size:22px;margin:0}.page-back,.link-btn{border:0;background:#eaf7fd;color:#174f70;border-radius:13px;font-weight:900;padding:10px}.link-btn{background:transparent;color:#1995cc}.notifications-list{padding:12px}.notif-row{display:grid;grid-template-columns:48px 1fr 56px;gap:10px;align-items:center;background:#fff;border:1px solid var(--line);border-radius:18px;padding:11px;margin:8px 0;cursor:pointer}.notif-row.unread{background:#fff9cf;border-color:#f3d75d}.notif-thumb{width:54px;height:54px;border-radius:12px;object-fit:cover;background:#eef}.notif-text b{display:block}.notif-text small{color:var(--muted)}.profile-page{padding-bottom:20px}.profile-page-head{background:linear-gradient(135deg,#bcecff,#fff1a8);padding:25px 15px;text-align:center}.profile-page-head .big-avatar{margin:0 auto 8px}.profile-page-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;padding:12px}.profile-page-stats div{text-align:center;background:#fff;border:1px solid var(--line);padding:12px 5px;border-radius:15px}.profile-page-stats b{display:block;font-size:20px}.profile-page-actions{padding:0 12px}.profile-page h2{padding:0 12px}.profile-page-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:3px}.profile-page-grid img{width:100%;aspect-ratio:1;object-fit:cover}.screen:not(.active){display:none!important}.screen.active{display:block!important}body.page-open{overflow:auto}.page-screen{min-height:calc(100vh - 140px)}@media(max-width:699px){header{position:fixed!important;left:0;right:0;top:0;max-width:650px;margin:auto}.app{padding-top:64px}.feed-tabs{top:0!important}.page-head{top:0}.screen:not(#feedScreen){padding-bottom:88px}nav{position:fixed!important}}`;
 document.head.appendChild(st);
}
injectV5();
function authMode(m){mode=m;$('#tabLogin').classList.toggle('active',m==='login');$('#tabSignup').classList.toggle('active',m==='signup');$('#signupFields').hidden=m!=='signup';$('#authBtn').textContent=m==='login'?'Se connecter':'Créer mon compte ☀️';$('#authMsg').textContent=''}
$('#tabLogin').onclick=()=>authMode('login');$('#tabSignup').onclick=()=>authMode('signup');
$('#authBtn').onclick=async()=>{const email=$('#email').value.trim(),password=$('#password').value,username=$('#username').value.trim();$('#authMsg').textContent='';if(!email||password.length<6)return $('#authMsg').textContent='Mail valide + mot de passe de 6 caractères minimum.';let r;if(mode==='signup'){if(username.length<3)return $('#authMsg').textContent='Pseudo : 3 caractères minimum.';r=await db.auth.signUp({email,password,options:{data:{username,country:'France'}}})}else r=await db.auth.signInWithPassword({email,password});if(r.error)return $('#authMsg').textContent=r.error.message;if(mode==='signup'&&!r.data.session){$('#authMsg').textContent='Compte créé. Connecte-toi maintenant.';return}await boot(r.data.user)};
$('#logout').onclick=async()=>{await db.auth.signOut();location.reload()};
async function boot(u){user=u;$('#auth').hidden=true;$('#app').hidden=false;await loadProfile();await Promise.all([loadFeed(),loadChallenges(),loadRanking(),loadMyPosts(),loadCommunity(),loadNotificationCount()]);setInterval(loadNotificationCount,10000);window.addEventListener('focus',loadNotificationCount)}
async function loadProfile(){const {data,error}=await db.from('profiles').select('*').eq('id',user.id).single();if(error)return console.error(error);profile=data;$('#profileName').textContent=data.username;$('#profileEmail').textContent=user.email||'';$('#trophies').textContent=data.beer_trophies||0;$('#level').textContent=data.level||1;const av=data.avatar_url?`<img src="${esc(data.avatar_url)}" style="width:100%;height:100%;object-fit:cover;border-radius:50%">`:'😎';$('#meAvatar').innerHTML=av;$('#profileAvatar').innerHTML=av}
async function loadFeed(){const feed=$('#feed');feed.innerHTML='<div class="empty"><h2>Chargement du feed…</h2></div>';let q=db.from('posts').select('id,user_id,image_url,caption,challenge_id,created_at').order('created_at',{ascending:false}).limit(80);if(feedMode==='challenge')q=q.not('challenge_id','is',null);const {data:posts,error}=await q;if(error){feed.innerHTML=`<div class="empty"><h2>Erreur du feed</h2><p>${esc(error.message)}</p></div>`;return}let rows=posts||[];if(feedMode==='friends'){const {data:f}=await db.from('friendships').select('requester_id,addressee_id,status').eq('status','accepted').or(`requester_id.eq.${user.id},addressee_id.eq.${user.id}`);const ids=new Set((f||[]).flatMap(x=>[x.requester_id,x.addressee_id]));ids.add(user.id);rows=rows.filter(x=>ids.has(x.user_id))}if(!rows.length)return renderFeed([]);const userIds=[...new Set(rows.map(x=>x.user_id))],challengeIds=[...new Set(rows.map(x=>x.challenge_id).filter(Boolean))],postIds=rows.map(x=>x.id);const [{data:ps},{data:cs},{data:rs}]=await Promise.all([db.from('profiles').select('id,username,avatar_url').in('id',userIds),challengeIds.length?db.from('challenges').select('id,title').in('id',challengeIds):Promise.resolve({data:[]}),db.from('reactions').select('post_id,user_id,reaction').in('post_id',postIds)]);const pm=new Map((ps||[]).map(x=>[x.id,x])),cm=new Map((cs||[]).map(x=>[x.id,x])),rm=new Map();for(const r of rs||[]){if(!rm.has(r.post_id))rm.set(r.post_id,[]);rm.get(r.post_id).push(r)}renderFeed(rows.map(p=>({...p,profile:pm.get(p.user_id),challenge:cm.get(p.challenge_id),reactions:rm.get(p.id)||[]})))}
function renderFeed(rows){if(!rows.length){$('#feed').innerHTML='<div class="empty"><h2>Pas encore de BeaufTime ☀️</h2></div>';return}$('#feed').innerHTML=rows.map(p=>{const c={beer:0,boar:0,masterclass:0,flipflop:0};let mine='';for(const r of p.reactions){c[r.reaction]++;if(r.user_id===user.id)mine=r.reaction}return `<article class="post-card" data-card="${p.id}"><img src="${esc(p.image_url)}"><div class="shade"></div><div class="post-info"><div class="userline" data-user-profile="${p.user_id}">${avatarHTML(p.profile,'uavatar')}<b>${esc(p.profile?.username||'Beauf')}</b></div>${p.challenge_id?`<span class="challenge-tag">🎯 ${esc(p.challenge?.title||'Défi')}</span>`:''}${p.caption?`<div class="caption">${esc(p.caption)}</div>`:''}<div class="reactions">${Object.entries(reactionLabels).map(([k,l])=>`<button class="react ${mine===k?'mine':''}" data-post="${p.id}" data-reaction="${k}">${l} <span>${c[k]}</span></button>`).join('')}</div></div></article>`}).join('');$$('.react').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleReaction(b.dataset.post,b.dataset.reaction)});$$('[data-user-profile]').forEach(x=>x.onclick=()=>openUserProfile(x.dataset.userProfile))}
async function refreshReactionBar(postId){const {data}=await db.from('reactions').select('user_id,reaction').eq('post_id',postId);const c={beer:0,boar:0,masterclass:0,flipflop:0};let mine='';for(const r of data||[]){c[r.reaction]++;if(r.user_id===user.id)mine=r.reaction}$$(`.react[data-post="${postId}"]`).forEach(b=>{b.classList.toggle('mine',b.dataset.reaction===mine);const s=b.querySelector('span');if(s)s.textContent=c[b.dataset.reaction]||0})}
async function toggleReaction(postId,type){const btn=$(`.react[data-post="${postId}"][data-reaction="${type}"]`);if(btn)btn.disabled=true;const {data:old}=await db.from('reactions').select('id,reaction').eq('post_id',postId).eq('user_id',user.id).maybeSingle();let error;if(old?.reaction===type)({error}=await db.from('reactions').delete().eq('id',old.id));else if(old)({error}=await db.from('reactions').update({reaction:type}).eq('id',old.id));else({error}=await db.from('reactions').insert({post_id:postId,user_id:user.id,reaction:type}));if(error)toast(error.message);await refreshReactionBar(postId);if(btn)btn.disabled=false}
$$('.feed-tabs button').forEach(b=>b.onclick=()=>{feedMode=b.dataset.feed;$$('.feed-tabs button').forEach(x=>x.classList.toggle('active',x===b));loadFeed()});
async function getFriendship(otherId){const {data}=await db.from('friendships').select('*').or(`and(requester_id.eq.${user.id},addressee_id.eq.${otherId}),and(requester_id.eq.${otherId},addressee_id.eq.${user.id})`).order('created_at',{ascending:false}).limit(1).maybeSingle();return data}
function friendButton(f,id){if(id===user.id)return '';if(!f)return `<button class="friend-btn" data-addfriend="${id}">+ Ami</button>`;if(f.status==='accepted')return '<button class="friend-btn friends" disabled>✓ Amis</button>';if(f.addressee_id===user.id)return `<button class="friend-btn accept" data-addfriend="${id}">Accepter</button>`;return '<button class="friend-btn pending" disabled>En attente</button>'}
async function friendAction(id){const f=await getFriendship(id);if(!f){const {error}=await db.from('friendships').insert({requester_id:user.id,addressee_id:id,status:'pending'});if(error)return toast(error.message);toast('Demande envoyée 🫂')}else if(f.status==='pending'&&f.addressee_id===user.id){const {error}=await db.from('friendships').update({status:'accepted'}).eq('id',f.id);if(error)return toast(error.message);toast('Vous êtes amis 🍻')}else toast(f.status==='accepted'?'Vous êtes déjà amis 🍻':'Demande déjà envoyée');loadCommunity();openUserProfile(id)}
async function loadCommunity(){if(!$('#usersList'))return;const search=$('#userSearch')?.value.trim()||'';let q=db.from('profiles').select('id,username,avatar_url,beer_trophies,level').neq('id',user.id).order('username').limit(100);if(search)q=q.ilike('username',`%${search}%`);const {data:people}=await q;const {data:rels}=await db.from('friendships').select('*').or(`requester_id.eq.${user.id},addressee_id.eq.${user.id}`);const fm=new Map();for(const f of rels||[])fm.set(f.requester_id===user.id?f.addressee_id:f.requester_id,f);$('#usersList').innerHTML=(people||[]).map(p=>`<div class="user-row" data-open-user="${p.id}">${avatarHTML(p)}<div class="user-meta"><b>${esc(p.username)}</b><small>${p.beer_trophies||0} 🏆 · Niveau ${p.level||1}</small></div>${friendButton(fm.get(p.id),p.id)}</div>`).join('');const req=(rels||[]).filter(f=>f.status==='pending'&&f.addressee_id===user.id);$('#friendRequestsWrap').hidden=!req.length;if(req.length){const ids=req.map(x=>x.requester_id);const {data:rp}=await db.from('profiles').select('id,username,avatar_url').in('id',ids);const m=new Map((rp||[]).map(x=>[x.id,x]));$('#friendRequests').innerHTML=req.map(f=>{const p=m.get(f.requester_id);return `<div class="request-row">${avatarHTML(p)}<div class="user-meta"><b>${esc(p?.username||'Beauf')}</b><small>veut devenir ton pote</small></div><button class="friend-btn accept" data-addfriend="${f.requester_id}">Accepter</button></div>`}).join('')}$$('[data-addfriend]').forEach(b=>b.onclick=e=>{e.stopPropagation();friendAction(b.dataset.addfriend)});$$('[data-open-user]').forEach(r=>r.onclick=()=>openUserProfile(r.dataset.openUser))}
async function openUserProfile(id){if(id===user.id)return go('profileScreen');go('userProfileScreen',false);const box=$('#userProfileContent');box.innerHTML='<div class="empty">Chargement du profil…</div>';const [{data:p},{data:posts},f]=await Promise.all([db.from('profiles').select('id,username,avatar_url,beer_trophies,level,country').eq('id',id).single(),db.from('posts').select('id,image_url').eq('user_id',id).order('created_at',{ascending:false}).limit(100),getFriendship(id)]);if(!p)return box.innerHTML='<div class="empty">Profil introuvable.</div>';box.innerHTML=`<div class="profile-page"><div class="profile-page-head">${avatarHTML(p,'big-avatar')}<h1>${esc(p.username)}</h1><span>${esc(p.country||'France')}</span></div><div class="profile-page-stats"><div><b>${p.beer_trophies||0}</b>🏆 Trophées</div><div><b>${p.level||1}</b>⭐ Niveau</div><div><b>${(posts||[]).length}</b>📸 Photos</div></div><div class="profile-page-actions">${friendButton(f,id)}</div><h2>Ses BeaufTimes</h2><div class="profile-page-grid">${(posts||[]).map(x=>`<img src="${esc(x.image_url)}">`).join('')||'<div class="empty">Aucune photo.</div>'}</div></div>`;$$('#userProfileContent [data-addfriend]').forEach(b=>b.onclick=()=>friendAction(b.dataset.addfriend))}
async function loadNotificationCount(){if(!user)return;const {count}=await db.from('notifications').select('*',{count:'exact',head:true}).eq('user_id',user.id).eq('is_read',false);const n=count||0,b=$('#notifBadge');if(b){b.textContent=n>99?'99+':n;b.hidden=!n}if(n>lastNotifCount&&lastNotifCount>0)toast('🔔 Nouvelle réaction sur ton BeaufTime !');lastNotifCount=n}
async function loadNotifications(){const box=$('#notificationsList');box.innerHTML='<div class="empty">Chargement…</div>';const {data:notifs,error}=await db.from('notifications').select('id,actor_id,post_id,reaction,is_read,created_at').eq('user_id',user.id).order('created_at',{ascending:false}).limit(100);if(error)return box.innerHTML=`<div class="empty">${esc(error.message)}</div>`;if(!(notifs||[]).length)return box.innerHTML='<div class="empty"><h2>Aucune notification 🔔</h2><p>Les réactions à tes photos apparaîtront ici.</p></div>';const actors=[...new Set(notifs.map(x=>x.actor_id))],posts=[...new Set(notifs.map(x=>x.post_id).filter(Boolean))];const [{data:ps},{data:po}]=await Promise.all([db.from('profiles').select('id,username,avatar_url').in('id',actors),posts.length?db.from('posts').select('id,image_url').in('id',posts):Promise.resolve({data:[]})]);const pm=new Map((ps||[]).map(x=>[x.id,x])),pom=new Map((po||[]).map(x=>[x.id,x]));box.innerHTML=notifs.map(n=>{const p=pm.get(n.actor_id),post=pom.get(n.post_id);const d=new Date(n.created_at).toLocaleString('fr-FR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'});return `<div class="notif-row ${n.is_read?'':'unread'}" data-notif="${n.id}" data-actor="${n.actor_id}">${avatarHTML(p)}<div class="notif-text"><b>${esc(p?.username||'Un Beauf')} a réagi ${reactionEmoji[n.reaction]||'🍺'}</b><small>${d}</small></div>${post?`<img class="notif-thumb" src="${esc(post.image_url)}">`:''}</div>`}).join('');$$('[data-notif]').forEach(r=>r.onclick=async()=>{await db.from('notifications').update({is_read:true}).eq('id',r.dataset.notif);await loadNotificationCount();openUserProfile(r.dataset.actor)})}
$('#notificationsBtn').onclick=()=>{go('notificationsScreen');loadNotifications()};$('#markAllRead').onclick=async()=>{await db.from('notifications').update({is_read:true}).eq('user_id',user.id).eq('is_read',false);await Promise.all([loadNotifications(),loadNotificationCount()])};
$('#userSearch').oninput=loadCommunity;$('#communityBtn').onclick=()=>{go('communityScreen');loadCommunity()};$('#findFriends').onclick=()=>{go('communityScreen');loadCommunity()};
async function loadChallenges(){const search=$('#challengeSearch').value.trim(),cat=$('#challengeCat').value;let q=db.from('challenges').select('id,title,category,reward').eq('active',true).order('id').limit(challengeLimit);if(search)q=q.ilike('title',`%${search}%`);if(cat&&cat!=='Tous')q=q.eq('category',cat);const {data}=await q;$('#challengeList').innerHTML=(data||[]).map(c=>`<div class="challenge"><div><b>${esc(c.title)}</b><small>${esc(c.category)}</small></div><div><span class="reward">🏆 +${c.reward}</span><button class="primary" data-challenge='${JSON.stringify(c).replace(/'/g,'&#39;')}'>Faire</button></div></div>`).join('');$$('[data-challenge]').forEach(b=>b.onclick=()=>{chosenChallenge=JSON.parse(b.dataset.challenge);$('#selectedChallenge').hidden=false;$('#selectedChallenge').textContent=`🎯 ${chosenChallenge.title} · 🏆 +${chosenChallenge.reward}`;go('postScreen');toast('Défi sélectionné 🎯')})}
$('#challengeSearch').oninput=()=>{challengeLimit=30;loadChallenges()};$('#challengeCat').onchange=()=>{challengeLimit=30;loadChallenges()};$('#moreChallenges').onclick=()=>{challengeLimit+=50;loadChallenges()};
function pickFile(f){if(!f)return;photoFile=f;$('#previewImg').src=URL.createObjectURL(f);$('#previewImg').hidden=false;$('#preview>span').hidden=true;$('#preview>b').hidden=true;$('#publish').disabled=false}$('#camera').onchange=e=>pickFile(e.target.files[0]);$('#gallery').onchange=e=>pickFile(e.target.files[0]);
$('#publish').onclick=async()=>{if(!photoFile)return;$('#publish').disabled=true;$('#uploadMsg').textContent='Envoi…';const ext=(photoFile.name.split('.').pop()||'jpg').toLowerCase(),path=`${user.id}/${Date.now()}-${crypto.randomUUID()}.${ext}`;const up=await db.storage.from('beauftime-photos').upload(path,photoFile,{cacheControl:'3600'});if(up.error){$('#uploadMsg').textContent=up.error.message;$('#publish').disabled=false;return}const {data:pub}=db.storage.from('beauftime-photos').getPublicUrl(path);const {data:p,error}=await db.from('posts').insert({user_id:user.id,image_url:pub.publicUrl,caption:$('#caption').value.trim()||null,challenge_id:chosenChallenge?.id||null}).select('id').single();if(error){$('#uploadMsg').textContent=error.message;$('#publish').disabled=false;return}if(chosenChallenge)await db.rpc('complete_challenge',{p_challenge_id:chosenChallenge.id,p_post_id:p.id});photoFile=null;chosenChallenge=null;$('#selectedChallenge').hidden=true;$('#previewImg').hidden=true;$('#preview>span').hidden=false;$('#preview>b').hidden=false;$('#caption').value='';$('#uploadMsg').textContent='';await Promise.all([loadProfile(),loadFeed(),loadRanking(),loadMyPosts()]);go('feedScreen');toast('☀️ BeaufTime publié !')};
async function loadRanking(){const {data}=await db.from('profiles').select('id,username,avatar_url,beer_trophies,level').order('beer_trophies',{ascending:false}).limit(100);$('#ranking').innerHTML=(data||[]).map((p,i)=>`<div class="rank-row" data-rank-user="${p.id}"><div class="rank-pos">${i<3?['🥇','🥈','🥉'][i]:i+1}</div>${avatarHTML(p)}<div><b>${esc(p.username)}</b><small>Niveau ${p.level||1}</small></div><div class="rank-score">${p.beer_trophies||0} 🏆</div></div>`).join('');$$('[data-rank-user]').forEach(x=>x.onclick=()=>openUserProfile(x.dataset.rankUser))}
async function loadMyPosts(){const {data}=await db.from('posts').select('image_url').eq('user_id',user.id).order('created_at',{ascending:false});$('#postsCount').textContent=(data||[]).length;$('#myGrid').innerHTML=(data||[]).map(p=>`<img src="${esc(p.image_url)}">`).join('')}
function go(id,scroll=true){currentScreen=id;$$('.screen').forEach(s=>s.classList.toggle('active',s.id===id));$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.screen===id));if(scroll&&id!=='feedScreen')window.scrollTo({top:0,behavior:'instant'});if(id==='rankScreen')loadRanking();if(id==='profileScreen'){loadProfile();loadMyPosts()}if(id==='communityScreen')loadCommunity()}
$$('.nav').forEach(n=>n.onclick=()=>go(n.dataset.screen));$('#homeLogo').onclick=()=>go('feedScreen');$('#meAvatar').onclick=()=>go('profileScreen');$$('.page-back').forEach(b=>b.onclick=()=>go('feedScreen'));
(async()=>{const {data:{session}}=await db.auth.getSession();if(session)await boot(session.user)})();
if('serviceWorker'in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js?v=5').catch(console.warn))}
