const SUPABASE_URL='https://gumzriegzesossdcypak.supabase.co';
const SUPABASE_KEY='sb_publishable_yzHxTr5YWx2CWTGDT3544w_Cp93fdUv';
const db=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let mode='login', user=null, profile=null, photoFile=null, chosenChallenge=null, challengeLimit=30, feedMode='all';
const reactions={beer:'🍺 Santé',boar:'🐗 Beauf certifié',masterclass:'😂 Masterclass',flipflop:'🩴 Claquettes d’or'};
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function authMode(m){mode=m;$('#tabLogin').classList.toggle('active',m==='login');$('#tabSignup').classList.toggle('active',m==='signup');$('#signupFields').hidden=m!=='signup';$('#authBtn').textContent=m==='login'?'Se connecter':'Créer mon compte ☀️';$('#authMsg').textContent=''}
$('#tabLogin').onclick=()=>authMode('login');$('#tabSignup').onclick=()=>authMode('signup');
$('#authBtn').onclick=async()=>{const email=$('#email').value.trim(),password=$('#password').value,username=$('#username').value.trim();$('#authMsg').textContent='';if(!email||password.length<6)return $('#authMsg').textContent='Mail valide + mot de passe de 6 caractères minimum.';let r;if(mode==='signup'){if(username.length<3)return $('#authMsg').textContent='Pseudo : 3 caractères minimum.';r=await db.auth.signUp({email,password,options:{data:{username,country:'France'},emailRedirectTo:location.href.split('#')[0]}})}else r=await db.auth.signInWithPassword({email,password});if(r.error)return $('#authMsg').textContent=r.error.message;if(mode==='signup'&&!r.data.session){$('#authMsg').textContent='Compte créé. Vérifie ton mail, puis reviens te connecter.';return}await boot(r.data.user)};
$('#logout').onclick=async()=>{await db.auth.signOut();location.reload()};
async function boot(u){user=u;$('#auth').hidden=true;$('#app').hidden=false;await loadProfile();await Promise.all([loadFeed(),loadChallenges(),loadRanking(),loadMyPosts()])}
async function loadProfile(){let {data,error}=await db.from('profiles').select('*').eq('id',user.id).single();if(error){console.error(error);return}profile=data;$('#profileName').textContent=data.username;$('#profileEmail').textContent=user.email||'';$('#trophies').textContent=data.beer_trophies;$('#level').textContent=data.level;$('#meAvatar').textContent='😎';$('#profileAvatar').textContent='😎'}
async function loadFeed(){let q=db.from('posts').select('id,user_id,image_url,caption,challenge_id,created_at,profiles(username),challenges(title),reactions(user_id,reaction)').order('created_at',{ascending:false}).limit(60);if(feedMode==='challenge')q=q.not('challenge_id','is',null);const {data,error}=await q;if(error){console.error(error);return}let rows=data||[];if(feedMode==='friends'){const {data:f}=await db.from('friendships').select('requester_id,addressee_id,status').eq('status','accepted').or(`requester_id.eq.${user.id},addressee_id.eq.${user.id}`);const ids=new Set((f||[]).flatMap(x=>[x.requester_id,x.addressee_id]));ids.add(user.id);rows=rows.filter(p=>ids.has(p.user_id))}renderFeed(rows)}
function renderFeed(rows){if(!rows.length){$('#feed').innerHTML='<div class="empty"><h2>Pas encore de BeaufTime ☀️</h2><p>Sois le premier à balancer une photo.</p></div>';return}$('#feed').innerHTML=rows.map(p=>{const counts={beer:0,boar:0,masterclass:0,flipflop:0};let mine='';for(const r of p.reactions||[]){counts[r.reaction]=(counts[r.reaction]||0)+1;if(r.user_id===user.id)mine=r.reaction}return `<article class="post-card"><img src="${esc(p.image_url)}"><div class="shade"></div><div class="post-info"><div class="userline"><div class="uavatar">😎</div><b>${esc(p.profiles?.username||'Beauf')}</b></div>${p.challenge_id?`<span class="challenge-tag">🎯 ${esc(p.challenges?.title||'Défi')}</span>`:''}${p.caption?`<div class="caption">${esc(p.caption)}</div>`:''}<div class="reactions">${Object.entries(reactions).map(([k,l])=>`<button class="react ${mine===k?'mine':''}" data-post="${p.id}" data-reaction="${k}">${l} ${counts[k]}</button>`).join('')}</div></div></article>`}).join('');$$('.react').forEach(b=>b.onclick=()=>toggleReaction(b.dataset.post,b.dataset.reaction))}
async function toggleReaction(postId,type){const {data:old}=await db.from('reactions').select('id,reaction').eq('post_id',postId).eq('user_id',user.id).maybeSingle();if(old?.reaction===type)await db.from('reactions').delete().eq('id',old.id);else if(old)await db.from('reactions').update({reaction:type}).eq('id',old.id);else await db.from('reactions').insert({post_id:postId,user_id:user.id,reaction:type});loadFeed()}
$$('.feed-tabs button').forEach(b=>b.onclick=()=>{feedMode=b.dataset.feed;$$('.feed-tabs button').forEach(x=>x.classList.toggle('active',x===b));loadFeed()});
async function loadChallenges(){const search=$('#challengeSearch').value.trim(),cat=$('#challengeCat').value;let q=db.from('challenges').select('id,title,category,reward').eq('active',true).order('id').limit(challengeLimit);if(search)q=q.ilike('title',`%${search}%`);if(cat&&cat!=='Tous')q=q.eq('category',cat);const {data,error}=await q;if(error)return console.error(error);$('#challengeList').innerHTML=(data||[]).map(c=>`<div class="challenge"><div><b>${esc(c.title)}</b><small>${esc(c.category)}</small></div><div><span class="reward">🏆 +${c.reward}</span><button class="primary" data-challenge='${JSON.stringify(c).replace(/'/g,'&#39;')}'>Faire</button></div></div>`).join('');$$('[data-challenge]').forEach(b=>b.onclick=()=>{chosenChallenge=JSON.parse(b.dataset.challenge);$('#selectedChallenge').hidden=false;$('#selectedChallenge').textContent=`🎯 ${chosenChallenge.title} · 🏆 +${chosenChallenge.reward}`;go('postScreen');toast('Défi sélectionné 🎯')})}
$('#challengeSearch').oninput=()=>{challengeLimit=30;loadChallenges()};$('#challengeCat').onchange=()=>{challengeLimit=30;loadChallenges()};$('#moreChallenges').onclick=()=>{challengeLimit+=50;loadChallenges()};
function pickFile(f){if(!f)return;photoFile=f;$('#previewImg').src=URL.createObjectURL(f);$('#previewImg').hidden=false;$('#preview>span').hidden=true;$('#preview>b').hidden=true;$('#publish').disabled=false}$('#camera').onchange=e=>pickFile(e.target.files[0]);$('#gallery').onchange=e=>pickFile(e.target.files[0]);
$('#publish').onclick=async()=>{if(!photoFile)return;$('#publish').disabled=true;$('#uploadMsg').textContent='Envoi de la masterclass…';const ext=(photoFile.name.split('.').pop()||'jpg').toLowerCase();const path=`${user.id}/${Date.now()}-${crypto.randomUUID()}.${ext}`;let up=await db.storage.from('beauftime-photos').upload(path,photoFile,{cacheControl:'3600',upsert:false});if(up.error){$('#uploadMsg').textContent=up.error.message;$('#publish').disabled=false;return}const {data:pub}=db.storage.from('beauftime-photos').getPublicUrl(path);const {data:p,error}=await db.from('posts').insert({user_id:user.id,image_url:pub.publicUrl,caption:$('#caption').value.trim()||null,challenge_id:chosenChallenge?.id||null}).select('id').single();if(error){$('#uploadMsg').textContent=error.message;$('#publish').disabled=false;return}if(chosenChallenge){const {data:r,error:re}=await db.rpc('complete_challenge',{p_challenge_id:chosenChallenge.id,p_post_id:p.id});if(!re&&r?.[0])toast(`🏆 +${r[0].reward} trophées bière !`)}else toast('☀️ BeaufTime publié !');photoFile=null;chosenChallenge=null;$('#selectedChallenge').hidden=true;$('#previewImg').hidden=true;$('#preview>span').hidden=false;$('#preview>b').hidden=false;$('#caption').value='';$('#uploadMsg').textContent='';await loadProfile();await Promise.all([loadFeed(),loadRanking(),loadMyPosts()]);go('feedScreen')};
async function loadRanking(){const {data,error}=await db.from('profiles').select('id,username,beer_trophies,level,country').order('beer_trophies',{ascending:false}).limit(100);if(error)return console.error(error);$('#ranking').innerHTML=(data||[]).map((p,i)=>`<div class="rank-row"><div class="rank-pos">${i<3?['🥇','🥈','🥉'][i]:i+1}</div><div>😎</div><div><b>${esc(p.username)}</b><small>Niveau ${p.level}</small></div><div class="rank-score">${p.beer_trophies} 🏆</div></div>`).join('')}
async function loadMyPosts(){const {data}=await db.from('posts').select('image_url').eq('user_id',user.id).order('created_at',{ascending:false});$('#postsCount').textContent=(data||[]).length;$('#myGrid').innerHTML=(data||[]).map(p=>`<img src="${esc(p.image_url)}">`).join('')}
function go(id){$$('.screen').forEach(s=>s.classList.toggle('active',s.id===id));$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.screen===id));if(id==='rankScreen')loadRanking();if(id==='profileScreen'){loadProfile();loadMyPosts()}if(id==='feedScreen')loadFeed()}$$('.nav').forEach(n=>n.onclick=()=>go(n.dataset.screen));$('#homeLogo').onclick=()=>go('feedScreen');$('#meAvatar').onclick=()=>go('profileScreen');
(async()=>{const {data:{session}}=await db.auth.getSession();if(session)await boot(session.user)})();
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.warn));}
