const SUPABASE_URL='https://gumzriegzesossdcypak.supabase.co';
const SUPABASE_KEY='sb_publishable_yzHxTr5YWx2CWTGDT3544w_Cp93fdUv';
const db=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let mode='login',user=null,profile=null,photoFile=null,chosenChallenge=null,challengeLimit=30,feedMode='all';
const reactions={beer:'🍺 Santé',boar:'🐗 Beauf certifié',masterclass:'😂 Masterclass',flipflop:'🩴 Claquettes d’or'};
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function avatarHTML(p,cls='mini-avatar'){return `<div class="${cls}">${p?.avatar_url?`<img src="${esc(p.avatar_url)}" alt="">`:'😎'}</div>`}
function authMode(m){mode=m;$('#tabLogin').classList.toggle('active',m==='login');$('#tabSignup').classList.toggle('active',m==='signup');$('#signupFields').hidden=m!=='signup';$('#authBtn').textContent=m==='login'?'Se connecter':'Créer mon compte ☀️';$('#authMsg').textContent=''}
$('#tabLogin').onclick=()=>authMode('login');$('#tabSignup').onclick=()=>authMode('signup');
$('#authBtn').onclick=async()=>{const email=$('#email').value.trim(),password=$('#password').value,username=$('#username').value.trim();$('#authMsg').textContent='';if(!email||password.length<6)return $('#authMsg').textContent='Mail valide + mot de passe de 6 caractères minimum.';let r;if(mode==='signup'){if(username.length<3)return $('#authMsg').textContent='Pseudo : 3 caractères minimum.';r=await db.auth.signUp({email,password,options:{data:{username,country:'France'}}})}else r=await db.auth.signInWithPassword({email,password});if(r.error)return $('#authMsg').textContent=r.error.message;if(mode==='signup'&&!r.data.session){$('#authMsg').textContent='Compte créé. Essaie maintenant de te connecter.';return}await boot(r.data.user)};
$('#logout').onclick=async()=>{await db.auth.signOut();location.reload()};
async function boot(u){user=u;$('#auth').hidden=true;$('#app').hidden=false;await loadProfile();await Promise.all([loadFeed(),loadChallenges(),loadRanking(),loadMyPosts(),loadCommunity()])}
async function loadProfile(){const {data,error}=await db.from('profiles').select('*').eq('id',user.id).single();if(error){console.error('profile',error);return}profile=data;$('#profileName').textContent=data.username;$('#profileEmail').textContent=user.email||'';$('#trophies').textContent=data.beer_trophies||0;$('#level').textContent=data.level||1;$('#meAvatar').innerHTML=data.avatar_url?`<img src="${esc(data.avatar_url)}" style="width:100%;height:100%;object-fit:cover;border-radius:50%">`:'😎';$('#profileAvatar').innerHTML=data.avatar_url?`<img src="${esc(data.avatar_url)}" style="width:100%;height:100%;object-fit:cover">`:'😎'}

async function loadFeed(){
  const feed=$('#feed'); feed.innerHTML='<div class="empty"><h2>Chargement du feed…</h2></div>';
  let q=db.from('posts').select('id,user_id,image_url,caption,challenge_id,created_at').order('created_at',{ascending:false}).limit(80);
  if(feedMode==='challenge')q=q.not('challenge_id','is',null);
  const {data:posts,error}=await q;
  if(error){console.error('feed posts',error);feed.innerHTML=`<div class="empty"><h2>Erreur du feed</h2><p>${esc(error.message)}</p></div>`;return}
  let rows=posts||[];
  if(feedMode==='friends'){
    const {data:f,error:fe}=await db.from('friendships').select('requester_id,addressee_id,status').eq('status','accepted').or(`requester_id.eq.${user.id},addressee_id.eq.${user.id}`);
    if(fe)console.error('friends feed',fe);
    const ids=new Set((f||[]).flatMap(x=>[x.requester_id,x.addressee_id]));ids.add(user.id);rows=rows.filter(p=>ids.has(p.user_id));
  }
  if(!rows.length){renderFeed([]);return}
  const userIds=[...new Set(rows.map(x=>x.user_id))]; const challengeIds=[...new Set(rows.map(x=>x.challenge_id).filter(Boolean))]; const postIds=rows.map(x=>x.id);
  const [{data:profiles},{data:challenges},{data:reacts}]=await Promise.all([
    db.from('profiles').select('id,username,avatar_url').in('id',userIds),
    challengeIds.length?db.from('challenges').select('id,title').in('id',challengeIds):Promise.resolve({data:[]}),
    db.from('reactions').select('id,post_id,user_id,reaction').in('post_id',postIds)
  ]);
  const pm=new Map((profiles||[]).map(x=>[x.id,x]));const cm=new Map((challenges||[]).map(x=>[x.id,x]));const rm=new Map();for(const r of reacts||[]){if(!rm.has(r.post_id))rm.set(r.post_id,[]);rm.get(r.post_id).push(r)}
  rows=rows.map(p=>({...p,profile:pm.get(p.user_id),challenge:cm.get(p.challenge_id),reactions:rm.get(p.id)||[]}));renderFeed(rows)
}
function renderFeed(rows){if(!rows.length){$('#feed').innerHTML=`<div class="empty"><h2>${feedMode==='friends'?'Aucune photo d’ami pour le moment':'Pas encore de BeaufTime ☀️'}</h2><p>${feedMode==='friends'?'Ajoute des potes avec le bouton 👥 en haut.':'Sois le premier à balancer une photo.'}</p></div>`;return}$('#feed').innerHTML=rows.map(p=>{const counts={beer:0,boar:0,masterclass:0,flipflop:0};let mine='';for(const r of p.reactions||[]){counts[r.reaction]=(counts[r.reaction]||0)+1;if(r.user_id===user.id)mine=r.reaction}return `<article class="post-card"><img src="${esc(p.image_url)}" alt="BeaufTime"><div class="shade"></div><div class="post-info"><div class="userline" data-user-profile="${p.user_id}">${avatarHTML(p.profile,'uavatar')}<b>${esc(p.profile?.username||'Beauf')}</b></div>${p.challenge_id?`<span class="challenge-tag">🎯 ${esc(p.challenge?.title||'Défi')}</span>`:''}${p.caption?`<div class="caption">${esc(p.caption)}</div>`:''}<div class="reactions">${Object.entries(reactions).map(([k,l])=>`<button class="react ${mine===k?'mine':''}" data-post="${p.id}" data-reaction="${k}">${l} ${counts[k]}</button>`).join('')}</div></div></article>`}).join('');$$('.react').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleReaction(b.dataset.post,b.dataset.reaction)});$$('[data-user-profile]').forEach(el=>el.onclick=()=>openUserProfile(el.dataset.userProfile))}
async function toggleReaction(postId,type){const {data:old}=await db.from('reactions').select('id,reaction').eq('post_id',postId).eq('user_id',user.id).maybeSingle();if(old?.reaction===type)await db.from('reactions').delete().eq('id',old.id);else if(old)await db.from('reactions').update({reaction:type}).eq('id',old.id);else await db.from('reactions').insert({post_id:postId,user_id:user.id,reaction:type});loadFeed()}
$$('.feed-tabs button').forEach(b=>b.onclick=()=>{feedMode=b.dataset.feed;$$('.feed-tabs button').forEach(x=>x.classList.toggle('active',x===b));loadFeed()});

async function getFriendship(otherId){const {data,error}=await db.from('friendships').select('*').or(`and(requester_id.eq.${user.id},addressee_id.eq.${otherId}),and(requester_id.eq.${otherId},addressee_id.eq.${user.id})`).order('created_at',{ascending:false}).limit(1).maybeSingle();if(error)console.error('friendship',error);return data}
async function friendAction(otherId){const f=await getFriendship(otherId);if(!f){const {error}=await db.from('friendships').insert({requester_id:user.id,addressee_id:otherId,status:'pending'});if(error)return toast(error.message);toast('Demande envoyée 🫂')}else if(f.status==='pending'&&f.addressee_id===user.id){const {error}=await db.from('friendships').update({status:'accepted'}).eq('id',f.id);if(error)return toast(error.message);toast('Vous êtes amis 🍻')}else if(f.status==='accepted'){toast('Vous êtes déjà amis 🍻')}else toast('Demande déjà envoyée');await loadCommunity();await openUserProfile(otherId);if(feedMode==='friends')loadFeed()}
function friendButton(f,otherId){if(otherId===user.id)return '';if(!f)return `<button class="friend-btn" data-addfriend="${otherId}">+ Ami</button>`;if(f.status==='accepted')return `<button class="friend-btn friends" disabled>✓ Amis</button>`;if(f.addressee_id===user.id)return `<button class="friend-btn accept" data-addfriend="${otherId}">Accepter</button>`;return `<button class="friend-btn pending" disabled>En attente</button>`}
async function loadCommunity(){
  const search=$('#userSearch')?.value.trim()||'';let q=db.from('profiles').select('id,username,avatar_url,beer_trophies,level,country').neq('id',user.id).order('username').limit(100);if(search)q=q.ilike('username',`%${search}%`);const {data:users,error}=await q;if(error){console.error(error);return}
  const {data:friends}=await db.from('friendships').select('*').or(`requester_id.eq.${user.id},addressee_id.eq.${user.id}`);const fm=new Map();for(const f of friends||[]){const oid=f.requester_id===user.id?f.addressee_id:f.requester_id;if(!fm.has(oid)||new Date(f.created_at)>new Date(fm.get(oid).created_at))fm.set(oid,f)}
  $('#usersList').innerHTML=(users||[]).map(p=>`<div class="user-row" data-open-user="${p.id}">${avatarHTML(p)}<div class="user-meta"><b>${esc(p.username)}</b><small>${p.beer_trophies||0} 🏆 · Niveau ${p.level||1}</small></div>${friendButton(fm.get(p.id),p.id)}</div>`).join('')||'<div class="empty">Aucun utilisateur trouvé.</div>';
  const reqs=(friends||[]).filter(f=>f.status==='pending'&&f.addressee_id===user.id);$('#friendRequestsWrap').hidden=!reqs.length;if(reqs.length){const ids=reqs.map(x=>x.requester_id);const {data:rp}=await db.from('profiles').select('id,username,avatar_url').in('id',ids);const map=new Map((rp||[]).map(x=>[x.id,x]));$('#friendRequests').innerHTML=reqs.map(f=>{const p=map.get(f.requester_id);return `<div class="request-row">${avatarHTML(p)}<div class="user-meta"><b>${esc(p?.username||'Beauf')}</b><small>veut devenir ton pote</small></div><button class="friend-btn accept" data-addfriend="${f.requester_id}">Accepter</button></div>`}).join('')}
  $$('[data-addfriend]').forEach(b=>b.onclick=e=>{e.stopPropagation();friendAction(b.dataset.addfriend)});$$('[data-open-user]').forEach(r=>r.onclick=()=>openUserProfile(r.dataset.openUser))
}
async function openUserProfile(id){
  if(id===user.id){go('profileScreen');return}go('communityScreen');const box=$('#userDetail');box.hidden=false;box.innerHTML='<div class="empty">Chargement du profil…</div>';
  const [{data:p,error},{data:posts},{data:f}]=await Promise.all([db.from('profiles').select('id,username,avatar_url,beer_trophies,level,country').eq('id',id).single(),db.from('posts').select('id,image_url,created_at').eq('user_id',id).order('created_at',{ascending:false}).limit(60),getFriendship(id)]);
  if(error||!p){box.innerHTML='<div class="empty">Profil introuvable.</div>';return}box.innerHTML=`<div class="user-detail-head">${avatarHTML(p,'big-avatar')}<h2>${esc(p.username)}</h2><span>${esc(p.country||'France')}</span></div><div class="user-detail-stats"><div><b>${p.beer_trophies||0}</b>🏆 Trophées</div><div><b>${p.level||1}</b>⭐ Niveau</div><div><b>${(posts||[]).length}</b>📸 Photos</div></div><div class="user-detail-actions">${friendButton(f,id)}</div><h3>Ses BeaufTimes</h3><div class="user-detail-grid">${(posts||[]).map(x=>`<img src="${esc(x.image_url)}" alt="">`).join('')||'<div class="empty">Aucune photo.</div>'}</div>`;$$('#userDetail [data-addfriend]').forEach(b=>b.onclick=()=>friendAction(b.dataset.addfriend));box.scrollIntoView({behavior:'smooth',block:'start'})
}
$('#userSearch').oninput=()=>loadCommunity();$('#communityBtn').onclick=()=>{go('communityScreen');loadCommunity()};$('#findFriends').onclick=()=>{go('communityScreen');loadCommunity()};

async function loadChallenges(){const search=$('#challengeSearch').value.trim(),cat=$('#challengeCat').value;let q=db.from('challenges').select('id,title,category,reward').eq('active',true).order('id').limit(challengeLimit);if(search)q=q.ilike('title',`%${search}%`);if(cat&&cat!=='Tous')q=q.eq('category',cat);const {data,error}=await q;if(error)return console.error(error);$('#challengeList').innerHTML=(data||[]).map(c=>`<div class="challenge"><div><b>${esc(c.title)}</b><small>${esc(c.category)}</small></div><div><span class="reward">🏆 +${c.reward}</span><button class="primary" data-challenge='${JSON.stringify(c).replace(/'/g,'&#39;')}'>Faire</button></div></div>`).join('');$$('[data-challenge]').forEach(b=>b.onclick=()=>{chosenChallenge=JSON.parse(b.dataset.challenge);$('#selectedChallenge').hidden=false;$('#selectedChallenge').textContent=`🎯 ${chosenChallenge.title} · 🏆 +${chosenChallenge.reward}`;go('postScreen');toast('Défi sélectionné 🎯')})}
$('#challengeSearch').oninput=()=>{challengeLimit=30;loadChallenges()};$('#challengeCat').onchange=()=>{challengeLimit=30;loadChallenges()};$('#moreChallenges').onclick=()=>{challengeLimit+=50;loadChallenges()};
function pickFile(f){if(!f)return;photoFile=f;$('#previewImg').src=URL.createObjectURL(f);$('#previewImg').hidden=false;$('#preview>span').hidden=true;$('#preview>b').hidden=true;$('#publish').disabled=false}$('#camera').onchange=e=>pickFile(e.target.files[0]);$('#gallery').onchange=e=>pickFile(e.target.files[0]);
$('#publish').onclick=async()=>{if(!photoFile)return;$('#publish').disabled=true;$('#uploadMsg').textContent='Envoi de la masterclass…';const ext=(photoFile.name.split('.').pop()||'jpg').toLowerCase();const path=`${user.id}/${Date.now()}-${crypto.randomUUID()}.${ext}`;let up=await db.storage.from('beauftime-photos').upload(path,photoFile,{cacheControl:'3600',upsert:false});if(up.error){$('#uploadMsg').textContent=up.error.message;$('#publish').disabled=false;return}const {data:pub}=db.storage.from('beauftime-photos').getPublicUrl(path);const {data:p,error}=await db.from('posts').insert({user_id:user.id,image_url:pub.publicUrl,caption:$('#caption').value.trim()||null,challenge_id:chosenChallenge?.id||null}).select('id').single();if(error){$('#uploadMsg').textContent=error.message;$('#publish').disabled=false;return}if(chosenChallenge){const {data:r,error:re}=await db.rpc('complete_challenge',{p_challenge_id:chosenChallenge.id,p_post_id:p.id});if(!re&&r?.[0])toast(`🏆 +${r[0].reward} trophées bière !`)}else toast('☀️ BeaufTime publié !');photoFile=null;chosenChallenge=null;$('#selectedChallenge').hidden=true;$('#previewImg').hidden=true;$('#preview>span').hidden=false;$('#preview>b').hidden=false;$('#caption').value='';$('#uploadMsg').textContent='';await loadProfile();await Promise.all([loadFeed(),loadRanking(),loadMyPosts(),loadCommunity()]);go('feedScreen')};
async function loadRanking(){const {data,error}=await db.from('profiles').select('id,username,avatar_url,beer_trophies,level,country').order('beer_trophies',{ascending:false}).limit(100);if(error)return console.error(error);$('#ranking').innerHTML=(data||[]).map((p,i)=>`<div class="rank-row" data-rank-user="${p.id}"><div class="rank-pos">${i<3?['🥇','🥈','🥉'][i]:i+1}</div>${avatarHTML(p)}<div><b>${esc(p.username)}</b><small>Niveau ${p.level||1}</small></div><div class="rank-score">${p.beer_trophies||0} 🏆</div></div>`).join('');$$('[data-rank-user]').forEach(r=>r.onclick=()=>openUserProfile(r.dataset.rankUser))}
async function loadMyPosts(){const {data}=await db.from('posts').select('image_url').eq('user_id',user.id).order('created_at',{ascending:false});$('#postsCount').textContent=(data||[]).length;$('#myGrid').innerHTML=(data||[]).map(p=>`<img src="${esc(p.image_url)}">`).join('')}
function go(id){$$('.screen').forEach(s=>s.classList.toggle('active',s.id===id));$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.screen===id));if(id==='rankScreen')loadRanking();if(id==='profileScreen'){loadProfile();loadMyPosts()}if(id==='feedScreen')loadFeed();if(id==='communityScreen')loadCommunity()}$$('.nav').forEach(n=>n.onclick=()=>go(n.dataset.screen));$('#homeLogo').onclick=()=>go('feedScreen');$('#meAvatar').onclick=()=>go('profileScreen');
(async()=>{const {data:{session}}=await db.auth.getSession();if(session)await boot(session.user)})();
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js?v=4').catch(console.warn));}
